server:
  port: 8090


spring:
  application:
    name: backend
  datasource:
    # මෙතන Database name එක smart_campus_db ලෙස වෙනස් කර ඇත
    url: jdbc:mysql://localhost:3306/smart_campus_db?createDatabaseIfNotExist=true
    username: root
    # ඔයාගේ අලුත් password එක මෙතනට දාන්න
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

module3:
  upload-dir: uploads/module3