spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://kaveen:Paf123@cluster0.bkzhhul.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0&tls=true
spring.mongodb.uri=mongodb+srv://kaveen:Paf123@cluster0.bkzhhul.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0&tls=true
spring.data.mongodb.auto-index-creation=true

server.port=8081

jwt.secret=SmartCampusSecretKey2024VeryLongAndSecureKeyForJWTSigning
jwt.expiration-ms=86400000

spring.security.oauth2.client.registration.google.client-id=927266091633-1ibh2m5m0d4vladd115qnd4f1140c9lt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

oauth2.redirect-uri=http://localhost:3000/oauth2/callback